<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function lab_migration_menu()
{
  $items = array();

  $items['lab_migration/proposal'] = array(
    'title' => 'Lab Migration Proposal',
    'description' => 'Lab Migration Proposal', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_proposal_form'),
    'access arguments' => array('create proposal'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'proposal.inc',
  );

  $items['lab_migration/labs'] = array(
    'title' => 'Migrated Labs',
    'description' => 'Migrated Labs', 
    'page callback' => 'migrated_labs',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'migrated_labs.inc',
  );

  /* for reviewers */
  $items['lab_migration/manage_proposal'] = array(
    'title' => 'Manage Lab Migration',
    'description' => 'Manage Lab Migration Proposals',
    'page callback' => '_proposal_pending',
    'access callback' => 'user_access',
    'access arguments' => array('manage proposal'),
    'file' => 'manage_proposal.inc',
  );
  $items['lab_migration/manage_proposal/pending'] = array(
    'title' => 'Pending Proposals',
    'description' => 'Pending Lab Migration Proposals Queue',
    'page callback' => '_proposal_pending',
    'access callback' => 'user_access',
    'access arguments' => array('manage proposal'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
    'file' => 'manage_proposal.inc',
  );
  $items['lab_migration/manage_proposal/pending_solution'] = array(
    'title' => 'Pending Solution',
    'description' => 'Pending Lab Migration Solution',
    'page callback' => '_proposal_pending_solution',
    'access callback' => 'user_access',
    'access arguments' => array('manage proposal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'file' => 'solution.inc',
  );
  $items['lab_migration/manage_proposal/all'] = array(
    'title' => 'All Proposals',
    'description' => 'All Proposals',
    'page callback' => '_proposal_all',
    'access callback' => 'user_access',
    'access arguments' => array('manage proposal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'file' => 'manage_proposal.inc',
  );
  $items['lab_migration/manage_proposal/approve'] = array(
    'title' => 'Approve Proposal',
    'description' => 'Approve Proposal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proposal_approval_form'),
    'access arguments' => array('manage proposal'),
    'type' => MENU_CALLBACK,
    'file' => 'manage_proposal.inc',
  );
  $items['lab_migration/manage_proposal/edit'] = array(
    'title' => 'Edit Proposal',
    'description' => 'Edit Proposal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proposal_edit_form'),
    'access arguments' => array('manage proposal'),
    'type' => MENU_CALLBACK,
    'file' => 'manage_proposal.inc',
  );
  $items['lab_migration/manage_proposal/solution'] = array(
    'title' => 'Proposal Solution',
    'description' => 'Proposal Solution',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proposal_solution_form'),
    'access arguments' => array('manage proposal'),
    'type' => MENU_CALLBACK,
    'file' => 'solution.inc',
  );

  /* for admin */
  $items['admin/settings/lab_migration'] = array(
    'title' => 'Lab Migration Settings',
    'description' => 'Lab Migration Settings', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lab_migration_settings_form'),
    'access arguments' => array('administer lab migration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function lab_migration_perm()
{
  return array('create proposal', 'manage proposal', 'administer lab migration');
}

/**
 * Implementation of hook_mail().
 */
function lab_migration_mail($key, &$message, $params)
{
  global $user;
  $language = $message['language'];
  switch ($key) {
    case 'proposal_received':
      /* initializing data */
      $proposal_q = db_query("SELECT * FROM {lab_migration_proposal} WHERE id = %d LIMIT 1", $params['proposal_received']['proposal_id']);
      $proposal_data = db_fetch_object($proposal_q);
      $user_data = user_load($params['proposal_received']['user_id']);
 
      $message['subject'] = t('[!site_name] Your Lab migration proposal has been received', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

We have received your proposal to migrate the lab in to Scilab, following details was submitted by you:

Name of the Proposer : ' . $proposal_data->name_title . ' ' . $proposal_data->name . '
Email : ' . $user_data->mail . '
Contact Phone No. : ' . $proposal_data->contact_ph . '
Department/Branch : ' . $proposal_data->department . '
University/Institute : ' .  $proposal_data->university . '
Title of the Lab : ' . $proposal_data->lab_title . '
Topic of the Problem : ' .  $proposal_data->problem_topic . '

Your proposal is under review and you will soon receive an email from us regarding the same.

Best Wishes,

Lab Migration Team
!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'proposal_disapproved':
      /* initializing data */
      $proposal_q = db_query("SELECT * FROM {lab_migration_proposal} WHERE id = %d LIMIT 1", $params['proposal_disapproved']['proposal_id']);
      $proposal_data = db_fetch_object($proposal_q);
      $user_data = user_load($params['proposal_disapproved']['user_id']);

      $message['subject'] = t('[!site_name] Your Lab migration proposal has been disapproved', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

Your following Lab migration proposal has been disapproved:

Reason for disapproval: ' . $proposal_data->message . '

Name of the Proposer : ' . $proposal_data->name_title . ' ' . $proposal_data->name . '
Email : ' . $user_data->mail . '
Contact Phone No. : ' . $proposal_data->contact_ph . '
Department/Branch : ' . $proposal_data->department . '
University/Institute : ' .  $proposal_data->university . '
Title of the Lab : ' . $proposal_data->lab_title . '
Topic of the Problem : ' .  $proposal_data->problem_topic . '

Best Wishes,

Lab Migration Team
!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'proposal_approved':
      /* initializing data */
      $proposal_q = db_query("SELECT * FROM {lab_migration_proposal} WHERE id = %d LIMIT 1", $params['proposal_approved']['proposal_id']);
      $proposal_data = db_fetch_object($proposal_q);
      $user_data = user_load($params['proposal_approved']['user_id']);

      $message['subject'] = t('[!site_name] Your Lab migration proposal has been approved', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

Your following Lab migration proposal has been approved and solution is in progress. You will receive an email from us as soon as we will upload the solution. Please note that your solution will be made available on the Scilab portal.

Name of the Proposer : ' . $proposal_data->name_title . ' ' . $proposal_data->name . '
Email : ' . $user_data->mail . '
Contact Phone No. : ' . $proposal_data->contact_ph . '
Department/Branch : ' . $proposal_data->department . '
University/Institute : ' .  $proposal_data->university . '
Title of the Lab : ' . $proposal_data->lab_title . '
Topic of the Problem : ' .  $proposal_data->problem_topic . '

Best Wishes,

Lab Migration Team
!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'solution_uploaded':
      /* initializing data */
      $dl_root_path = 'sites/default/files/lab_migration/';
      $proposal_q = db_query("SELECT * FROM {lab_migration_proposal} WHERE id = %d LIMIT 1", $params['solution_uploaded']['proposal_id']);
      $proposal_data = db_fetch_object($proposal_q);
      $sol_q = db_query("SELECT * FROM {lab_migration_files} WHERE link_id = %d AND filetype = 'A' LIMIT 1", $params['solution_uploaded']['proposal_id']);
      $sol_data = db_fetch_object($sol_q);

      $user_data = user_load($params['solution_uploaded']['user_id']);

      $message['subject'] = t('[!site_name] Solution to your Lab migration has been completed', array('!site_name' => variable_get('site_name', '')), $language->language);
      $message['body'] = t('
Dear !user_name,

Solution to your Lab migration has been completed and is available on http://scilab.in/lab_migration/labs

Name of the Proposer : ' . $proposal_data->name_title . ' ' . $proposal_data->name . '
Email : ' . $user_data->mail . '
Contact Phone No. : ' . $proposal_data->contact_ph . '
Department/Branch : ' . $proposal_data->department . '
University/Institute : ' .  $proposal_data->university . '
Title of the Lab : ' . $proposal_data->lab_title . '
Topic of the Problem : ' .  $proposal_data->problem_topic . '
Solution : ' . 'http://scilab.in/' . $dl_root_path . $sol_data->filepath . '

Best Wishes,

Lab Migration Team
!site_name', array('!site_name' => variable_get('site_name', ''), '!user_name' => $user_data->name), $language->language);
      break;

    case 'standard':
      $message['subject'] = $params['standard']['subject'];
      $message['body'] = $params['standard']['body'];
      break;
  }
}

/******************************************************************************/
/**************************** GENERAL FUNCTION ********************************/
/******************************************************************************/

function lab_migration_path()
{
  return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'sites/default/files/lab_migration/';
}

/******************************************************************************/
/*************************** VALIDATION FUNCTIONS *****************************/
/******************************************************************************/

function lab_migration_check_valid_filename($file_name)
{
  if (!preg_match('/^[0-9a-zA-Z\_\.\-]+$/', $file_name))
    return FALSE;
  else
    if (substr_count($file_name, ".") > 1)
      return FALSE;
    else
      return TRUE;
}

